<?php
/**
 * Mageplaza_Kb extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Mageplaza
 * @package        Mageplaza_Kb
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category subtree template
 *
 * @category    Mageplaza
 * @package     Mageplaza_Kb
 * @author      Ultimate Module Creator
 */
?>
<?php $_categorys = $this->getCategorys(); ?>
<?php if ($_categorys->getSize() > 0) :?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/mageplaza_kb/tree.js')?>"></script>
    <ul id="<?php echo $this->getUniqueId()?>">
        <?php foreach ($_categorys as $_category) : ?>
            <?php echo $this->drawCategory($_category);?>
        <?php endforeach;?>
    </ul>
    <script type="text/javascript">
        kbTree('<?php echo $this->getUniqueId()?>');
    </script>
<?php endif;?>
