<?php 
/**
 * Mageplaza_Kb extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Mageplaza
 * @package        Mageplaza_Kb
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Tag list template
 *
 * @category    Mageplaza
 * @package     Mageplaza_Kb
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_tags = $this->getTags(); ?>
<div class="page-title tag-title">
    <?php if (Mage::helper('mageplaza_kb/tag')->isRssEnabled()) : ?>
        <a href="<?php echo Mage::helper('mageplaza_kb/tag')->getRssUrl();?>" class="link-rss"><?php echo Mage::helper('mageplaza_kb')->__('Subscribe to RSS Feed')?></a>
    <?php endif;?>
    <h1><?php echo Mage::helper('mageplaza_kb')->__('Tags') ?></h1>
</div>
<?php if ($_tags->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="tag-list-container">
    <?php foreach ($_tags as $_tag) : ?>
        <div class="tag-list-item">
            <a href="<?php echo $_tag->getTagUrl()?>">
                <?php echo $_tag->getName();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('mageplaza_kb')->__('There are no tags at this moment');?>
<?php endif;?>
