<?php 
/**
 * Mageplaza_Kb extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Mageplaza
 * @package        Mageplaza_Kb
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Tag Article list template
 *
 * @category    Mageplaza
 * @package     Mageplaza_Kb
 * @author      Ultimate Module Creator
 */
?>
<?php $_articles = $this->getArticles(); ?>
<?php if ($_articles->getSize() > 0) :?>
<div class="page-title article-title">
    <h2><?php echo Mage::helper('mageplaza_kb')->__('Articles') ?></h2>
</div>
<div class="articles-list-container">
    <?php foreach ($_articles as $_article) : ?>
        <div class="article-list-item">
            <a href="<?php echo $_article->getArticleUrl()?>">
                <?php echo $_article->getName();?>
            </a><br />
        </div>
    <?php endforeach;?>
</div>
<?php endif;?>
