<?php
/**
 * YOU ARE USING FREE EXTENSION, THERE IS POWERED LINK IN FOOTER. YOU SHOULD KEEP THESE LINKS TO HELP US IMPROVE OUR PRODUCTS.
 * THANK YOU!
 */
?>
<div class="mp-footer"> <span class="mp-footer-links-light"> <h3> <a href="https://www.mageplaza.com/magento-faq/">Magento FAQ</a> powered by <a href="https://www.magecheckout.com/" target="_blank">Magento 2 One Step Checkout</a> <a href="https://www.bestonestepcheckout.com/" target="_blank">Magento 2 One Step Checkout extension</a> </h3> </span> </div>


