<?php 
/**
 * Mageplaza_Kb extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Mageplaza
 * @package        Mageplaza_Kb
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Article Category list template
 *
 * @category    Mageplaza
 * @package     Mageplaza_Kb
 * @author      Ultimate Module Creator
 */
?>
<?php $_categorys = $this->getCategorys(); ?>
<?php if ($_categorys->getSize() > 0) :?>
<div class="page-title category-title">
    <h2><?php echo Mage::helper('mageplaza_kb')->__('Categories') ?></h2>
</div>
<div class="categorys-list-container">
    <?php $list = array();?>
    <?php foreach ($_categorys as $_category) : ?>
            <?php $list[] = '<a href="'.$_category->getCategoryUrl().'"> '. $_category->getName(). '</a>'; ?>
    <?php endforeach;?>
    <?php echo implode(', ', $list);?>
</div>
<?php endif;?>
